version: "3"
services:
  directus:
    container_name: directus
    image: directus/directus:10.10.4
    ports:
      - 48056:8055
    volumes:
      - ./database:/directus/database
      - ./uploads:/directus/uploads
      - ./extensions:/directus/extensions
    networks:
      - directus
    environment:
      KEY: "FDNvN89q0UP"
      SECRET: "6116487be263"
      DB_CLIENT: "sqlite3"
      DB_FILENAME: "/directus/database/data.db"
      ADMIN_EMAIL: "abdelmomen1985@gmail.com"
      ADMIN_PASSWORD: "123456d6"
      WEBSOCKETS_ENABLED: "true"
      STORAGE_LOCATIONS: "cloudinary"
      STORAGE_CLOUDINARY_DRIVER: "cloudinary"
      STORAGE_CLOUDINARY_CLOUD_NAME: "dlg4nl1rx"
      STORAGE_CLOUDINARY_API_KEY: "248165738342725"
      STORAGE_CLOUDINARY_API_SECRET: "YsZhDdEGyymtoCPdaZLBjqjTtyA"
      STORAGE_CLOUDINARY_ACCESS_MODE: "public"

networks:
  directus:
